### ISSUE TITLE
[Issue]: int8 gemm pipeline build error

### ISSUE THREAD

**Issue by ZJLi2013** [ROCm/composable_kernel#2205]
### Problem Description

hi, CK experts,

tried to add an int8 pipeline, following ck-tile/03-gemm, by adding the following in warp_gemm_dispatcher:

```c++
// int8
template<> struct WarpGemmMfmaDispatcher<ck_tile::int8_t, ck_tile::int8_t, int32_t, 32, 32,  16, false> { using Type = WarpGemmMfma_i32_32x32x16_i8_i8; };
``` 

but got the following build error:

```yml
/composable_kernel/example/ck_tile/03_gemm/gemm_basic.cpp
fatal error: error in backend: Cannot select: intrinsic %llvm.amdgcn.mfma.i32.32x32x8i8
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
AMD clang version 19.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.4.0 25133 c7fe45cf4b819c5991fe208aaa96edf142730f1d)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-6.4.0/lib/llvm/bin
Configuration file: /opt/rocm-6.4.0/lib/llvm/bin/clang++.cfg
clang++: note: diagnostic msg: Error generating preprocessed source(s).
``` 

the base image here is `roch/pytorch:latest` ,

thanks for guidance

### Operating System

ubuntu 22.04

### CPU

ryzen

### GPU

AMD Instinct MI300

### ROCm Version

ROCm 6.0.0

**Comment by ZJLi2013** [comment]
also build on rocm-6.3.4, similar error: 

```yml
/composable_kernel/example/ck_tile/03_gemm/gemm_basic.cpp
fatal error: error in backend: Cannot select: intrinsic %llvm.amdgcn.mfma.i32.32x32x8i8
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
AMD clang version 18.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.3.4 25012 e5bf7e55c91490b07c49d8960fa7983d864936c4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/lib/llvm/bin
Configuration file: /opt/rocm-6.3.4/lib/llvm/bin/clang++.cfg
clang++: note: diagnostic msg: Error generating preprocessed source(s).

```
